language: java
sudo: false
dist: xenial

jdk:
  - openjdk8

script: travis_wait mvn verify --quiet --batch-mode -DbuildNumber=${TRAVIS_BUILD_NUMBER}

notifications:
  email:
    recipients:
     - eis@iki.fi
    on_success: change
    on_failure: always

after_failure:
  - cat target/surefire-reports/*.txt
